name: Build and deploy
on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: "The tag of the image to deploy"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --platform linux/amd64 --tag ${{ inputs.image-tag }}
