name: TestLogin
on:
  pull_request:
    branches:
    - trung
  push:
    branches:
    - trung
  workflow_dispatch:
jobs:
  # nodetest:
  #   runs-on: ubuntu-latest
  #   container: node:18
  #   steps:
  #     # - run: node --version
  #     # - run: npm --version
  #     - run: apt-get update
  #     - run: apt-get -qq install lsof
  #     - uses: actions/checkout@v3
  #     - run: npm i
  #     - run: node server.js &
  #     - run: npm run test
  #     - run: kill -9 $(lsof -t -i:5000)
  pytest:
    runs-on: ubuntu-latest
    container: nikolaik/python-nodejs:python3.11-nodejs18-alpine
    steps:
      - run: node --version 
      - run: python --version
      - run: npm --version
      - run: node server.js &
      - run: npm start &
      - run: kill -9 $(lsof -t -i:5000)
      - run: kill -9 $(lsof -t -i:3000)