name: Build and deploy
on:
  workflow_run:
    workflows: ["CI"]
    types: [requested]
    branches: [test/qthai]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --platform linux/amd64 --tag online-exam-app-api:"$(date +%s)"
